# Generated by Django 3.2.16 on 2023-01-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pictures')),
                ('name1', models.CharField(max_length=250)),
                ('desc1', models.TextField()),
            ],
        ),
    ]
